
REPO_NAME=chrisgarrett
PROJECT_NAME=galton
PROJECT_VERSION=0.0.1
IMAGE_NAME=$REPO_NAME/$PROJECT_NAME:$PROJECT_VERSION
LATEST_IMAGE_NAME=$REPO_NAME/$PROJECT_NAME:latest
CONTAINER_NAME=$PROJECT_NAME
DB_DIR=db
